namespace API.Entities;

public sealed class AppUser
{
    //Table users
    public string Id { get; set; } = Guid.NewGuid().ToString(); // for academic purposes here, but better to be generated by DB
    public required string DisplayName { get; set; }
    public required string Email { get; set; }
    public required byte[] PasswordHash { get; set; }
    public required byte[] PasswordSalt { get; set; }
}
